apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
commonLabels:
  app: pdc
configMapGenerator:
- name: kiwi-web
  envs: 
  - .env
namespace: kiwi
resources:
- pvc.yaml
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml